name: 'Site Config for stage'
description: 'The domain plus TLD and theme settings of the site to deploy'

config:
  sitepath: 'plottcreative.co.uk/stage/'
  stagefolder: 'plottcore'
  themepath: '/web/app/themes/plott-os/'
  environment: 'staging'
