name: Stage Deploy
on:
  push:
    branches:
      - "stage"
jobs:
  deploy_prod:
    name: Deploy Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get Site Path
        id: sitepath
        uses: KJ002/read-yaml@main
        with:
          file: "./.github/stageconfig.yml"
          key-path: '["config", "sitepath"]'

      - name: Get Stage Folder
        id: stagefolder
        uses: KJ002/read-yaml@main
        with:
          file: "./.github/stageconfig.yml"
          key-path: '["config", "stagefolder"]'

      - name: Get Theme Path
        if: success()
        id: themepath
        uses: KJ002/read-yaml@main
        with:
          file: "./.github/stageconfig.yml"
          key-path: '["config", "themepath"]'

      - name: Get site environment
        if: success()
        id: siteenv
        uses: KJ002/read-yaml@main
        with:
          file: "./.github/stageconfig.yml"
          key-path: '["config", "environment"]'

      - name: Check Site Folder Existence
        if: success()
        id: checksite
        uses: fifsky/ssh-action@master
        with:
          command: |
            if [ -d ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}} ]; then
              echo "Site folder exists."
              exit 0
            else
              echo "Site folder does not exist."
              echo "Creating stage folder"
              cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data}}
              mkdir ${{steps.stagefolder.outputs.data}}
              exit 0
            fi
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Check For Git Repository
        id: checkgitrepo
        uses: fifsky/ssh-action@master
        continue-on-error: true
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}/.git
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Create Git Repository
        id: creategitrepo
        if: steps.checkgitrepo.outcome == 'failure'
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}
            git init
            git remote add origin git@github.com:${{ github.repository }}.git
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: ReCheck For Git Repository
        id: recheckgitrepo
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}/.git
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Configure sparse-checkout to exclude changelog.md
        if: steps.recheckgitrepo.outcome == 'success'
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}
            git config core.sparseCheckout true
            echo "/*" > .git/info/sparse-checkout
            echo "!changelog.md" >> .git/info/sparse-checkout
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Pull Changes
        id: pullchanges
        if: steps.recheckgitrepo.outcome == 'success'
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}
            git checkout stage
            git pull origin stage
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Create and Update .env File
        if: steps.pullchanges.outcome == 'success'
        id: envfile
        uses: fifsky/ssh-action@master
        with:
          command: |
            cat << 'EOF' > ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}/.env
            DB_NAME=${{ secrets.DB_NAME_STAGE }}
            DB_USER=${{ secrets.PLOTT_STAGE_USER }}
            DB_PASSWORD=${{ secrets.PLOTT_STAGE_PASS }}
            
            # Optionally, you can use a data source name (DSN)
            # When using a DSN, you can remove the DB_NAME, DB_USER, DB_PASSWORD, and DB_HOST variables
            # DATABASE_URL='mysql://database_user:database_password@database_host:database_port/database_name'
            
            # Optional database variables
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PREFIX=${{ secrets.TABLE_PREFIX }}
            
            WP_HOME='https://stage.plott.co.uk/${{ steps.stagefolder.outputs.data }}'
            WP_SITEURL="${WP_HOME}/web/wp"
            WP_ENV='staging'
            
            # Specify optional debug.log path
            # WP_DEBUG_LOG='/path/to/debug.log'
            
            # Add AWS credentials
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
            # Generate your keys here: https://plott.co.uk/salts.html
            AUTH_KEY=${{ secrets.AUTH_KEY }}
            SECURE_AUTH_KEY=${{ secrets.SECURE_AUTH_KEY }}
            LOGGED_IN_KEY=${{ secrets.LOGGED_IN_KEY }}
            NONCE_KEY=${{ secrets.NONCE_KEY }}
            AUTH_SALT=${{ secrets.AUTH_SALT }}
            SECURE_AUTH_SALT=${{ secrets.SECURE_AUTH_SALT }}
            LOGGED_IN_SALT=${{ secrets.LOGGED_IN_SALT }}
            NONCE_SALT=${{ secrets.NONCE_SALT }}
            
            EOF
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Check for Root Composer dependencies
        if: steps.envfile.outcome == 'success'
        id: checkrootcomposer
        uses: fifsky/ssh-action@master
        with:
          command: |
            cat ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}/composer.json
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Install Composer Gravity Forms Plugin
        id: installgravityformsplugin
        run: |
          composer global config --no-plugins allow-plugins.piotrpress/composer-gravityforms true
          composer global require piotrpress/composer-gravityforms
          composer config --global http-basic.gravityapi.com key ${{ secrets.PLOTT_GRAVITY_KEY }}
        env:
          COMPOSER_ALLOW_SUPERUSER: "1"

      - name: Install Root Composer dependencies
        if: steps.checkrootcomposer.outcome == 'success'
        id: installrootcomposer
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}
            composer update
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev --quiet
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Build Theme
        if: steps.installrootcomposer.outcome == 'success'
        id: buildTheme
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}${{ steps.themepath.outputs.data }}
            npm install --quiet --no-progress --unsafe-perm=true --allow-root
            npm run prod
            rm -rf node_modules
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Theme Composer Install
        if: steps.buildTheme.outcome == 'success'
        id: installComposerTheme
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.PLOTT_ROOT_DIR }}${{ steps.sitepath.outputs.data }}${{steps.stagefolder.outputs.data}}${{ steps.themepath.outputs.data }}
            composer update
            composer install
          host: ${{ secrets.SOLO_HOST }}
          user: ${{ secrets.PLOTTDEPLOY_USER }}
          key: ${{ secrets.PLOTTDEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Web Push
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: always()
